phases:
  install:
    runtime-versions:
      # Specify runtime if needed, e.g., nodejs: 18
    commands:
      - echo Updating apt-get...
      - sudo apt-get update -y
      - echo Installing nginx...
      - sudo apt-get install -y nginx
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo Build phase...
      cp index.html /var/www/html
  post_build:
    commands:
      - echo Post-build phase...

artifacts:
  files:
    - /var/www/html/index.html
